import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider, Show, UserButton } from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="h-screen flex flex-col">
        <ClerkProvider>
          <div className="flex flex-col h-full w-full">
            <header className="flex justify-between items-center p-4 h-[10%]">
              <h1
                className="text-2xl md:text-3xl font-extrabold text-center
        bg-linear-to-r from-blue-400 via-purple-500 to-pink-500
        bg-clip-text text-transparent tracking-wider"
              >
                ASKMYPDF
              </h1>
              <UserButton />
            </header>

            <main className="h-[90%] overflow-hidden">{children}</main>
          </div>
        </ClerkProvider>
      </body>
    </html>
  );
}
